//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceGOLAfterBlackout.BIW {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BIW_SFM_Activity.STATO_GOL", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    public enum BIW_SFM_ActivitySTATO_GOL : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REMOTO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOCALE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUTOGENERANTE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MANUALE = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATESTRUTTURA = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ACK_PLC", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    public enum ACK_PLC : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERRORE = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLC_TIMEOUT_ACK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK_OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK_LISTA_PIENA = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK_STRPRD_NOK = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK_SSC_NOK = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK_CSS_NOK = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK_CF_NOK = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK_SeqNr_NOK = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK_TIO_SLAVE = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STATUS_INFO", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    [System.SerializableAttribute()]
    public partial struct STATUS_INFO : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NiceGOLAfterBlackout.BIW.ATTRIBUTI_CLIENT AttributiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NiceGOLAfterBlackout.BIW.BIW_SFM_ActivitySTATO_GOL ModalitàOperativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PlcOnLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServerOnLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatoImpostatoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NiceGOLAfterBlackout.BIW.BIW_SFM_ActivitySTATO_PROCESSO StatoProcessoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NiceGOLAfterBlackout.BIW.ATTRIBUTI_CLIENT Attributi {
            get {
                return this.AttributiField;
            }
            set {
                if ((this.AttributiField.Equals(value) != true)) {
                    this.AttributiField = value;
                    this.RaisePropertyChanged("Attributi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NiceGOLAfterBlackout.BIW.BIW_SFM_ActivitySTATO_GOL ModalitàOperativa {
            get {
                return this.ModalitàOperativaField;
            }
            set {
                if ((this.ModalitàOperativaField.Equals(value) != true)) {
                    this.ModalitàOperativaField = value;
                    this.RaisePropertyChanged("ModalitàOperativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PlcOnLine {
            get {
                return this.PlcOnLineField;
            }
            set {
                if ((this.PlcOnLineField.Equals(value) != true)) {
                    this.PlcOnLineField = value;
                    this.RaisePropertyChanged("PlcOnLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServerOnLine {
            get {
                return this.ServerOnLineField;
            }
            set {
                if ((this.ServerOnLineField.Equals(value) != true)) {
                    this.ServerOnLineField = value;
                    this.RaisePropertyChanged("ServerOnLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatoImpostatore {
            get {
                return this.StatoImpostatoreField;
            }
            set {
                if ((this.StatoImpostatoreField.Equals(value) != true)) {
                    this.StatoImpostatoreField = value;
                    this.RaisePropertyChanged("StatoImpostatore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NiceGOLAfterBlackout.BIW.BIW_SFM_ActivitySTATO_PROCESSO StatoProcesso {
            get {
                return this.StatoProcessoField;
            }
            set {
                if ((this.StatoProcessoField.Equals(value) != true)) {
                    this.StatoProcessoField = value;
                    this.RaisePropertyChanged("StatoProcesso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATTRIBUTI_CLIENT", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    [System.SerializableAttribute()]
    public partial struct ATTRIBUTI_CLIENT : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNumericoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsImpostatoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMasterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NiceGOLAfterBlackout.BIW.LineaGol LineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OffsetSlaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NiceGOLAfterBlackout.BIW.RANGE RangeCFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NiceGOLAfterBlackout.BIW.RANGE RangeCSSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NiceGOLAfterBlackout.BIW.RANGE RangeSSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NiceGOLAfterBlackout.BIW.RANGE RangeSequenzeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UpdateStrutturaProdottoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNumerico {
            get {
                return this.IdNumericoField;
            }
            set {
                if ((this.IdNumericoField.Equals(value) != true)) {
                    this.IdNumericoField = value;
                    this.RaisePropertyChanged("IdNumerico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsImpostatore {
            get {
                return this.IsImpostatoreField;
            }
            set {
                if ((this.IsImpostatoreField.Equals(value) != true)) {
                    this.IsImpostatoreField = value;
                    this.RaisePropertyChanged("IsImpostatore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMaster {
            get {
                return this.IsMasterField;
            }
            set {
                if ((this.IsMasterField.Equals(value) != true)) {
                    this.IsMasterField = value;
                    this.RaisePropertyChanged("IsMaster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NiceGOLAfterBlackout.BIW.LineaGol Linea {
            get {
                return this.LineaField;
            }
            set {
                if ((this.LineaField.Equals(value) != true)) {
                    this.LineaField = value;
                    this.RaisePropertyChanged("Linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OffsetSlave {
            get {
                return this.OffsetSlaveField;
            }
            set {
                if ((this.OffsetSlaveField.Equals(value) != true)) {
                    this.OffsetSlaveField = value;
                    this.RaisePropertyChanged("OffsetSlave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NiceGOLAfterBlackout.BIW.RANGE RangeCF {
            get {
                return this.RangeCFField;
            }
            set {
                if ((this.RangeCFField.Equals(value) != true)) {
                    this.RangeCFField = value;
                    this.RaisePropertyChanged("RangeCF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NiceGOLAfterBlackout.BIW.RANGE RangeCSS {
            get {
                return this.RangeCSSField;
            }
            set {
                if ((this.RangeCSSField.Equals(value) != true)) {
                    this.RangeCSSField = value;
                    this.RaisePropertyChanged("RangeCSS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NiceGOLAfterBlackout.BIW.RANGE RangeSSC {
            get {
                return this.RangeSSCField;
            }
            set {
                if ((this.RangeSSCField.Equals(value) != true)) {
                    this.RangeSSCField = value;
                    this.RaisePropertyChanged("RangeSSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NiceGOLAfterBlackout.BIW.RANGE RangeSequenze {
            get {
                return this.RangeSequenzeField;
            }
            set {
                if ((this.RangeSequenzeField.Equals(value) != true)) {
                    this.RangeSequenzeField = value;
                    this.RaisePropertyChanged("RangeSequenze");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UpdateStrutturaProdotto {
            get {
                return this.UpdateStrutturaProdottoField;
            }
            set {
                if ((this.UpdateStrutturaProdottoField.Equals(value) != true)) {
                    this.UpdateStrutturaProdottoField = value;
                    this.RaisePropertyChanged("UpdateStrutturaProdotto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BIW_SFM_Activity.STATO_PROCESSO", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    public enum BIW_SFM_ActivitySTATO_PROCESSO : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FERMO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AVVIATO = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaGol", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    [System.SerializableAttribute()]
    public partial struct LineaGol : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DecrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsImpostatoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Decrizione {
            get {
                return this.DecrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DecrizioneField, value) != true)) {
                    this.DecrizioneField = value;
                    this.RaisePropertyChanged("Decrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipmentID {
            get {
                return this.EquipmentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentIDField, value) != true)) {
                    this.EquipmentIDField = value;
                    this.RaisePropertyChanged("EquipmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsImpostatore {
            get {
                return this.IsImpostatoreField;
            }
            set {
                if ((this.IsImpostatoreField.Equals(value) != true)) {
                    this.IsImpostatoreField = value;
                    this.RaisePropertyChanged("IsImpostatore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RANGE", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    [System.SerializableAttribute()]
    public partial struct RANGE : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Max {
            get {
                return this.MaxField;
            }
            set {
                if ((this.MaxField.Equals(value) != true)) {
                    this.MaxField = value;
                    this.RaisePropertyChanged("Max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Min {
            get {
                return this.MinField;
            }
            set {
                if ((this.MinField.Equals(value) != true)) {
                    this.MinField = value;
                    this.RaisePropertyChanged("Min");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRG_INFO", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    [System.SerializableAttribute()]
    public partial struct PRG_INFO : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumElementiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SSC_UniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SSC_UnpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeqNr_UniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeqNr_UnpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet UNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet UNPField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumElementi {
            get {
                return this.NumElementiField;
            }
            set {
                if ((this.NumElementiField.Equals(value) != true)) {
                    this.NumElementiField = value;
                    this.RaisePropertyChanged("NumElementi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SSC_Uni {
            get {
                return this.SSC_UniField;
            }
            set {
                if ((this.SSC_UniField.Equals(value) != true)) {
                    this.SSC_UniField = value;
                    this.RaisePropertyChanged("SSC_Uni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SSC_Unp {
            get {
                return this.SSC_UnpField;
            }
            set {
                if ((this.SSC_UnpField.Equals(value) != true)) {
                    this.SSC_UnpField = value;
                    this.RaisePropertyChanged("SSC_Unp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeqNr_Uni {
            get {
                return this.SeqNr_UniField;
            }
            set {
                if ((this.SeqNr_UniField.Equals(value) != true)) {
                    this.SeqNr_UniField = value;
                    this.RaisePropertyChanged("SeqNr_Uni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeqNr_Unp {
            get {
                return this.SeqNr_UnpField;
            }
            set {
                if ((this.SeqNr_UnpField.Equals(value) != true)) {
                    this.SeqNr_UnpField = value;
                    this.RaisePropertyChanged("SeqNr_Unp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeLista {
            get {
                return this.SizeListaField;
            }
            set {
                if ((this.SizeListaField.Equals(value) != true)) {
                    this.SizeListaField = value;
                    this.RaisePropertyChanged("SizeLista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet UNI {
            get {
                return this.UNIField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIField, value) != true)) {
                    this.UNIField = value;
                    this.RaisePropertyChanged("UNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet UNP {
            get {
                return this.UNPField;
            }
            set {
                if ((object.ReferenceEquals(this.UNPField, value) != true)) {
                    this.UNPField = value;
                    this.RaisePropertyChanged("UNP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOIP_INFO", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    [System.SerializableAttribute()]
    public partial struct LOIP_INFO : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeListaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeLista {
            get {
                return this.SizeListaField;
            }
            set {
                if ((this.SizeListaField.Equals(value) != true)) {
                    this.SizeListaField = value;
                    this.RaisePropertyChanged("SizeLista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STRPRODOTTO_INFO", Namespace="http://schemas.datacontract.org/2004/07/BIW_SFM")]
    [System.SerializableAttribute()]
    public partial struct STRPRODOTTO_INFO : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeOfPageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPages {
            get {
                return this.NumOfPagesField;
            }
            set {
                if ((this.NumOfPagesField.Equals(value) != true)) {
                    this.NumOfPagesField = value;
                    this.RaisePropertyChanged("NumOfPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeOfPage {
            get {
                return this.SizeOfPageField;
            }
            set {
                if ((this.SizeOfPageField.Equals(value) != true)) {
                    this.SizeOfPageField = value;
                    this.RaisePropertyChanged("SizeOfPage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BIW.IBIW_SFM_GUI")]
    public interface IBIW_SFM_GUI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_ModalitàOperativa", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_ModalitàOperativaResponse")]
        bool Set_ModalitàOperativa(NiceGOLAfterBlackout.BIW.BIW_SFM_ActivitySTATO_GOL modalità);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_ModalitàOperativa", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_ModalitàOperativaResponse")]
        System.Threading.Tasks.Task<bool> Set_ModalitàOperativaAsync(NiceGOLAfterBlackout.BIW.BIW_SFM_ActivitySTATO_GOL modalità);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_StrutturaProdotto", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_StrutturaProdottoResponse")]
        System.Data.DataSet Get_StrutturaProdotto(int Pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_StrutturaProdotto", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_StrutturaProdottoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_StrutturaProdottoAsync(int Pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_StrutturaProdotto", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_StrutturaProdottoResponse")]
        bool Set_StrutturaProdotto(System.Data.DataSet struttura, int Pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_StrutturaProdotto", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_StrutturaProdottoResponse")]
        System.Threading.Tasks.Task<bool> Set_StrutturaProdottoAsync(System.Data.DataSet struttura, int Pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Add_NuovoOrdine", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Add_NuovoOrdineResponse")]
        NiceGOLAfterBlackout.BIW.ACK_PLC Add_NuovoOrdine(System.Data.DataSet ordine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Add_NuovoOrdine", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Add_NuovoOrdineResponse")]
        System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.ACK_PLC> Add_NuovoOrdineAsync(System.Data.DataSet ordine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_Status", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_StatusResponse")]
        NiceGOLAfterBlackout.BIW.STATUS_INFO Get_Status();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_Status", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_StatusResponse")]
        System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.STATUS_INFO> Get_StatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ListaPRG", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ListaPRGResponse")]
        System.Data.DataSet Get_ListaPRG();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ListaPRG", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ListaPRGResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_ListaPRGAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ListaPRG_Info", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ListaPRG_InfoResponse")]
        NiceGOLAfterBlackout.BIW.PRG_INFO Get_ListaPRG_Info();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ListaPRG_Info", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ListaPRG_InfoResponse")]
        System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.PRG_INFO> Get_ListaPRG_InfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_ListaPRG_Size", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_ListaPRG_SizeResponse")]
        bool Set_ListaPRG_Size(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_ListaPRG_Size", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_ListaPRG_SizeResponse")]
        System.Threading.Tasks.Task<bool> Set_ListaPRG_SizeAsync(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Reset_ListaPRG", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Reset_ListaPRGResponse")]
        bool Reset_ListaPRG();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Reset_ListaPRG", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Reset_ListaPRGResponse")]
        System.Threading.Tasks.Task<bool> Reset_ListaPRGAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Shift_ListaPRG", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Shift_ListaPRGResponse")]
        bool Shift_ListaPRG();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Shift_ListaPRG", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Shift_ListaPRGResponse")]
        System.Threading.Tasks.Task<bool> Shift_ListaPRGAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ListaLOIP", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ListaLOIPResponse")]
        System.Data.DataSet Get_ListaLOIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ListaLOIP", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ListaLOIPResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_ListaLOIPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ListaLOIP_Info", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ListaLOIP_InfoResponse")]
        NiceGOLAfterBlackout.BIW.LOIP_INFO Get_ListaLOIP_Info();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ListaLOIP_Info", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ListaLOIP_InfoResponse")]
        System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.LOIP_INFO> Get_ListaLOIP_InfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_ListaLOIP_Size", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_ListaLOIP_SizeResponse")]
        bool Set_ListaLOIP_Size(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_ListaLOIP_Size", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_ListaLOIP_SizeResponse")]
        System.Threading.Tasks.Task<bool> Set_ListaLOIP_SizeAsync(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Reset_ListaLOIP", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Reset_ListaLOIPResponse")]
        bool Reset_ListaLOIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Reset_ListaLOIP", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Reset_ListaLOIPResponse")]
        System.Threading.Tasks.Task<bool> Reset_ListaLOIPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Shift_ListaLOIP", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Shift_ListaLOIPResponse")]
        bool Shift_ListaLOIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Shift_ListaLOIP", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Shift_ListaLOIPResponse")]
        System.Threading.Tasks.Task<bool> Shift_ListaLOIPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_PaccoOrdini", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_PaccoOrdiniResponse")]
        System.Data.DataSet Get_PaccoOrdini();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_PaccoOrdini", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_PaccoOrdiniResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_PaccoOrdiniAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_RangePaccoOrdini", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_RangePaccoOrdiniResponse")]
        bool Set_RangePaccoOrdini(int seqStart, int seqStop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_RangePaccoOrdini", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_RangePaccoOrdiniResponse")]
        System.Threading.Tasks.Task<bool> Set_RangePaccoOrdiniAsync(int seqStart, int seqStop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/StartProcess", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/StartProcessResponse")]
        bool StartProcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/StartProcess", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/StartProcessResponse")]
        System.Threading.Tasks.Task<bool> StartProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/StopProcess", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/StopProcessResponse")]
        bool StopProcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/StopProcess", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/StopProcessResponse")]
        System.Threading.Tasks.Task<bool> StopProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_RangeAutogenerante", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_RangeAutogeneranteResponse")]
        bool Set_RangeAutogenerante(int seqStart, int SSC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Set_RangeAutogenerante", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Set_RangeAutogeneranteResponse")]
        System.Threading.Tasks.Task<bool> Set_RangeAutogeneranteAsync(int seqStart, int SSC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_StrutturaProdotto_Info", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_StrutturaProdotto_InfoResponse")]
        NiceGOLAfterBlackout.BIW.STRPRODOTTO_INFO Get_StrutturaProdotto_Info();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_StrutturaProdotto_Info", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_StrutturaProdotto_InfoResponse")]
        System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.STRPRODOTTO_INFO> Get_StrutturaProdotto_InfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ConfigFile", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ConfigFileResponse")]
        System.Xml.Linq.XElement Get_ConfigFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/Get_ConfigFile", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/Get_ConfigFileResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> Get_ConfigFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/ExportPaccoOrdini", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/ExportPaccoOrdiniResponse")]
        bool ExportPaccoOrdini(string PathDestinazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/ExportPaccoOrdini", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/ExportPaccoOrdiniResponse")]
        System.Threading.Tasks.Task<bool> ExportPaccoOrdiniAsync(string PathDestinazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/ImportPaccoOrdini", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/ImportPaccoOrdiniResponse")]
        bool ImportPaccoOrdini(string PathSorgente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/ImportPaccoOrdini", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/ImportPaccoOrdiniResponse")]
        System.Threading.Tasks.Task<bool> ImportPaccoOrdiniAsync(string PathSorgente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/ExportConfigurazione", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/ExportConfigurazioneResponse")]
        bool ExportConfigurazione(string PathDestinazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/ExportConfigurazione", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/ExportConfigurazioneResponse")]
        System.Threading.Tasks.Task<bool> ExportConfigurazioneAsync(string PathDestinazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/ImportConfigurazione", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/ImportConfigurazioneResponse")]
        bool ImportConfigurazione(string PathSorgente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/ImportConfigurazione", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/ImportConfigurazioneResponse")]
        System.Threading.Tasks.Task<bool> ImportConfigurazioneAsync(string PathSorgente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/SRV_Set_ListaPRG_Size", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/SRV_Set_ListaPRG_SizeResponse")]
        bool SRV_Set_ListaPRG_Size(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/SRV_Set_ListaPRG_Size", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/SRV_Set_ListaPRG_SizeResponse")]
        System.Threading.Tasks.Task<bool> SRV_Set_ListaPRG_SizeAsync(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/SRV_Reset_ListaPRG", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/SRV_Reset_ListaPRGResponse")]
        bool SRV_Reset_ListaPRG();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIW_SFM_GUI/SRV_Reset_ListaPRG", ReplyAction="http://tempuri.org/IBIW_SFM_GUI/SRV_Reset_ListaPRGResponse")]
        System.Threading.Tasks.Task<bool> SRV_Reset_ListaPRGAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBIW_SFM_GUIChannel : NiceGOLAfterBlackout.BIW.IBIW_SFM_GUI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BIW_SFM_GUIClient : System.ServiceModel.ClientBase<NiceGOLAfterBlackout.BIW.IBIW_SFM_GUI>, NiceGOLAfterBlackout.BIW.IBIW_SFM_GUI {
        
        public BIW_SFM_GUIClient() {
        }
        
        public BIW_SFM_GUIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BIW_SFM_GUIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BIW_SFM_GUIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BIW_SFM_GUIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Set_ModalitàOperativa(NiceGOLAfterBlackout.BIW.BIW_SFM_ActivitySTATO_GOL modalità) {
            return base.Channel.Set_ModalitàOperativa(modalità);
        }
        
        public System.Threading.Tasks.Task<bool> Set_ModalitàOperativaAsync(NiceGOLAfterBlackout.BIW.BIW_SFM_ActivitySTATO_GOL modalità) {
            return base.Channel.Set_ModalitàOperativaAsync(modalità);
        }
        
        public System.Data.DataSet Get_StrutturaProdotto(int Pagina) {
            return base.Channel.Get_StrutturaProdotto(Pagina);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_StrutturaProdottoAsync(int Pagina) {
            return base.Channel.Get_StrutturaProdottoAsync(Pagina);
        }
        
        public bool Set_StrutturaProdotto(System.Data.DataSet struttura, int Pagina) {
            return base.Channel.Set_StrutturaProdotto(struttura, Pagina);
        }
        
        public System.Threading.Tasks.Task<bool> Set_StrutturaProdottoAsync(System.Data.DataSet struttura, int Pagina) {
            return base.Channel.Set_StrutturaProdottoAsync(struttura, Pagina);
        }
        
        public NiceGOLAfterBlackout.BIW.ACK_PLC Add_NuovoOrdine(System.Data.DataSet ordine) {
            return base.Channel.Add_NuovoOrdine(ordine);
        }
        
        public System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.ACK_PLC> Add_NuovoOrdineAsync(System.Data.DataSet ordine) {
            return base.Channel.Add_NuovoOrdineAsync(ordine);
        }
        
        public NiceGOLAfterBlackout.BIW.STATUS_INFO Get_Status() {
            return base.Channel.Get_Status();
        }
        
        public System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.STATUS_INFO> Get_StatusAsync() {
            return base.Channel.Get_StatusAsync();
        }
        
        public System.Data.DataSet Get_ListaPRG() {
            return base.Channel.Get_ListaPRG();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_ListaPRGAsync() {
            return base.Channel.Get_ListaPRGAsync();
        }
        
        public NiceGOLAfterBlackout.BIW.PRG_INFO Get_ListaPRG_Info() {
            return base.Channel.Get_ListaPRG_Info();
        }
        
        public System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.PRG_INFO> Get_ListaPRG_InfoAsync() {
            return base.Channel.Get_ListaPRG_InfoAsync();
        }
        
        public bool Set_ListaPRG_Size(int size) {
            return base.Channel.Set_ListaPRG_Size(size);
        }
        
        public System.Threading.Tasks.Task<bool> Set_ListaPRG_SizeAsync(int size) {
            return base.Channel.Set_ListaPRG_SizeAsync(size);
        }
        
        public bool Reset_ListaPRG() {
            return base.Channel.Reset_ListaPRG();
        }
        
        public System.Threading.Tasks.Task<bool> Reset_ListaPRGAsync() {
            return base.Channel.Reset_ListaPRGAsync();
        }
        
        public bool Shift_ListaPRG() {
            return base.Channel.Shift_ListaPRG();
        }
        
        public System.Threading.Tasks.Task<bool> Shift_ListaPRGAsync() {
            return base.Channel.Shift_ListaPRGAsync();
        }
        
        public System.Data.DataSet Get_ListaLOIP() {
            return base.Channel.Get_ListaLOIP();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_ListaLOIPAsync() {
            return base.Channel.Get_ListaLOIPAsync();
        }
        
        public NiceGOLAfterBlackout.BIW.LOIP_INFO Get_ListaLOIP_Info() {
            return base.Channel.Get_ListaLOIP_Info();
        }
        
        public System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.LOIP_INFO> Get_ListaLOIP_InfoAsync() {
            return base.Channel.Get_ListaLOIP_InfoAsync();
        }
        
        public bool Set_ListaLOIP_Size(int size) {
            return base.Channel.Set_ListaLOIP_Size(size);
        }
        
        public System.Threading.Tasks.Task<bool> Set_ListaLOIP_SizeAsync(int size) {
            return base.Channel.Set_ListaLOIP_SizeAsync(size);
        }
        
        public bool Reset_ListaLOIP() {
            return base.Channel.Reset_ListaLOIP();
        }
        
        public System.Threading.Tasks.Task<bool> Reset_ListaLOIPAsync() {
            return base.Channel.Reset_ListaLOIPAsync();
        }
        
        public bool Shift_ListaLOIP() {
            return base.Channel.Shift_ListaLOIP();
        }
        
        public System.Threading.Tasks.Task<bool> Shift_ListaLOIPAsync() {
            return base.Channel.Shift_ListaLOIPAsync();
        }
        
        public System.Data.DataSet Get_PaccoOrdini() {
            return base.Channel.Get_PaccoOrdini();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_PaccoOrdiniAsync() {
            return base.Channel.Get_PaccoOrdiniAsync();
        }
        
        public bool Set_RangePaccoOrdini(int seqStart, int seqStop) {
            return base.Channel.Set_RangePaccoOrdini(seqStart, seqStop);
        }
        
        public System.Threading.Tasks.Task<bool> Set_RangePaccoOrdiniAsync(int seqStart, int seqStop) {
            return base.Channel.Set_RangePaccoOrdiniAsync(seqStart, seqStop);
        }
        
        public bool StartProcess() {
            return base.Channel.StartProcess();
        }
        
        public System.Threading.Tasks.Task<bool> StartProcessAsync() {
            return base.Channel.StartProcessAsync();
        }
        
        public bool StopProcess() {
            return base.Channel.StopProcess();
        }
        
        public System.Threading.Tasks.Task<bool> StopProcessAsync() {
            return base.Channel.StopProcessAsync();
        }
        
        public bool Set_RangeAutogenerante(int seqStart, int SSC) {
            return base.Channel.Set_RangeAutogenerante(seqStart, SSC);
        }
        
        public System.Threading.Tasks.Task<bool> Set_RangeAutogeneranteAsync(int seqStart, int SSC) {
            return base.Channel.Set_RangeAutogeneranteAsync(seqStart, SSC);
        }
        
        public NiceGOLAfterBlackout.BIW.STRPRODOTTO_INFO Get_StrutturaProdotto_Info() {
            return base.Channel.Get_StrutturaProdotto_Info();
        }
        
        public System.Threading.Tasks.Task<NiceGOLAfterBlackout.BIW.STRPRODOTTO_INFO> Get_StrutturaProdotto_InfoAsync() {
            return base.Channel.Get_StrutturaProdotto_InfoAsync();
        }
        
        public System.Xml.Linq.XElement Get_ConfigFile() {
            return base.Channel.Get_ConfigFile();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> Get_ConfigFileAsync() {
            return base.Channel.Get_ConfigFileAsync();
        }
        
        public bool ExportPaccoOrdini(string PathDestinazione) {
            return base.Channel.ExportPaccoOrdini(PathDestinazione);
        }
        
        public System.Threading.Tasks.Task<bool> ExportPaccoOrdiniAsync(string PathDestinazione) {
            return base.Channel.ExportPaccoOrdiniAsync(PathDestinazione);
        }
        
        public bool ImportPaccoOrdini(string PathSorgente) {
            return base.Channel.ImportPaccoOrdini(PathSorgente);
        }
        
        public System.Threading.Tasks.Task<bool> ImportPaccoOrdiniAsync(string PathSorgente) {
            return base.Channel.ImportPaccoOrdiniAsync(PathSorgente);
        }
        
        public bool ExportConfigurazione(string PathDestinazione) {
            return base.Channel.ExportConfigurazione(PathDestinazione);
        }
        
        public System.Threading.Tasks.Task<bool> ExportConfigurazioneAsync(string PathDestinazione) {
            return base.Channel.ExportConfigurazioneAsync(PathDestinazione);
        }
        
        public bool ImportConfigurazione(string PathSorgente) {
            return base.Channel.ImportConfigurazione(PathSorgente);
        }
        
        public System.Threading.Tasks.Task<bool> ImportConfigurazioneAsync(string PathSorgente) {
            return base.Channel.ImportConfigurazioneAsync(PathSorgente);
        }
        
        public bool SRV_Set_ListaPRG_Size(int size) {
            return base.Channel.SRV_Set_ListaPRG_Size(size);
        }
        
        public System.Threading.Tasks.Task<bool> SRV_Set_ListaPRG_SizeAsync(int size) {
            return base.Channel.SRV_Set_ListaPRG_SizeAsync(size);
        }
        
        public bool SRV_Reset_ListaPRG() {
            return base.Channel.SRV_Reset_ListaPRG();
        }
        
        public System.Threading.Tasks.Task<bool> SRV_Reset_ListaPRGAsync() {
            return base.Channel.SRV_Reset_ListaPRGAsync();
        }
    }
}
